spring:
  application:
    # use k8s service name
    name: sckd-user-service-provider
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      loadbalancer:
        mode: SERVICE
      reload:
        enabled: true
        strategy: refresh
        mode: polling
        # verifying changes period second
        period: 10s
        namespaces:
          - default
      config:
        enabled: true
        fail-fast: true
        include-profile-specific-sources: true
        namespace: default
      discovery:
        all-namespaces: true
        cache-loading-timeout-seconds: 60
        enabled: true

server:
  port: 8700

logging:
  config: classpath:logback-springboot.xml

print-server-address:
  ignore-parent-context: true

info:
  tags:
    environment: test
  app: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"